version: '3.3'

services:

  app:
    image: nicolaj/php-playground
    build: .
    container_name: play
    env_file:
      - .env
    ports:
      - "1234:80"
    volumes:
      - ./public_html:/var/www/html

