version: '3.3'

services:

  app:
    image: glaux/php-playground
    build: .
    container_name: play
    env_file:
      - .env
    # ports:
    #   - "1234:80"
    expose:
      - "80"
    volumes:
      - ./public_html:/var/www/html

networks:
  default:
    external:
      name: webproxy
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
